-- ============================================================
-- MUEBLERIA ERP - Mapeo físico PostgreSQL

BEGIN;

-- ------------------------------------------------------------
-- Tablas catálogo / maestras
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS area (
                                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    nombre          VARCHAR(100) NOT NULL,
    CONSTRAINT pk_area PRIMARY KEY (id),
    CONSTRAINT uq_area_nombre UNIQUE (nombre)
    );

CREATE TABLE IF NOT EXISTS rol (
                                   id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   rol             VARCHAR(100) NOT NULL,
    activo	    BOOLEAN NOT NULL DEFAULT TRUE,
    descripcion     VARCHAR(255),
    CONSTRAINT pk_rol PRIMARY KEY (id),
    CONSTRAINT uq_rol_rol UNIQUE (rol)
    );

CREATE TABLE IF NOT EXISTS permiso (
                                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       codigo          VARCHAR(100) NOT NULL,
    descripcion     VARCHAR(255),
    CONSTRAINT pk_permiso PRIMARY KEY (id),
    CONSTRAINT uq_permiso_codigo UNIQUE (codigo)
    );

CREATE TABLE IF NOT EXISTS cliente (
                                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       nombre          VARCHAR(150) NOT NULL,
    nit             VARCHAR(30) NOT NULL,
    direccion       VARCHAR(255),
    telefono        VARCHAR(30),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_cliente PRIMARY KEY (id),
    CONSTRAINT uq_cliente_nit UNIQUE (nit)
    );

CREATE TABLE IF NOT EXISTS proveedor (
                                         id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                         nombre              VARCHAR(150) NOT NULL,
    direccion           VARCHAR(255),
    telefono_contacto   VARCHAR(30),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_proveedor PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS producto (
                                        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                        nombre              VARCHAR(150) NOT NULL,
    categoria           VARCHAR(100) NOT NULL,
    precio              NUMERIC(12,2) NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    sku                 VARCHAR(60) NOT NULL,
    existencia_minima   INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_producto PRIMARY KEY (id),
    CONSTRAINT uq_producto_sku UNIQUE (sku),
    CONSTRAINT ck_producto_precio CHECK (precio >= 0),
    CONSTRAINT ck_producto_existencia_minima CHECK (existencia_minima >= 0)
    );

-- ------------------------------------------------------------
-- Empleados y seguridad
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS empleado (
                                        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                        name                VARCHAR(150) NOT NULL,
    usuario             VARCHAR(100) NOT NULL,
    rol_id              BIGINT NOT NULL,
    password            VARCHAR(255) NOT NULL,
    dpi                 VARCHAR(30) NOT NULL,
    numero_telefono     VARCHAR(30),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    area_id             BIGINT,
    CONSTRAINT pk_empleado PRIMARY KEY (id),
    CONSTRAINT uq_empleado_usuario UNIQUE (usuario),
    CONSTRAINT uq_empleado_dpi UNIQUE (dpi),
    CONSTRAINT fk_empleado_rol
    FOREIGN KEY (rol_id) REFERENCES rol(id),
    CONSTRAINT fk_empleado_area
    FOREIGN KEY (area_id) REFERENCES area(id)
    );

CREATE TABLE IF NOT EXISTS rol_permiso (
                                           rol_id              BIGINT NOT NULL,
                                           permiso_id          BIGINT NOT NULL,
                                           CONSTRAINT pk_rol_permiso PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT fk_rol_permiso_rol
    FOREIGN KEY (rol_id) REFERENCES rol(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_rol_permiso_permiso
    FOREIGN KEY (permiso_id) REFERENCES permiso(id)
    ON DELETE CASCADE
    );

-- ------------------------------------------------------------
-- Inventario
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS inventario (
                                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                          producto_id     BIGINT NOT NULL,
                                          existencia      INTEGER NOT NULL DEFAULT 0,
                                          CONSTRAINT pk_inventario PRIMARY KEY (id),
    CONSTRAINT uq_inventario_producto UNIQUE (producto_id),
    CONSTRAINT fk_inventario_producto
    FOREIGN KEY (producto_id) REFERENCES producto(id),
    CONSTRAINT ck_inventario_existencia CHECK (existencia >= 0)
    );

CREATE TABLE IF NOT EXISTS inventario_log (
                                              id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                              inventario_id           BIGINT NOT NULL,
                                              catidad_cambio          INTEGER NOT NULL,
                                              existencia_resultante   INTEGER NOT NULL,
                                              tipo_movimiento         VARCHAR(50) NOT NULL,
    creado_en               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    origen_tipo             VARCHAR(50),
    origen_id               BIGINT,
    CONSTRAINT pk_inventario_log PRIMARY KEY (id),
    CONSTRAINT fk_inventario_log_inventario
    FOREIGN KEY (inventario_id) REFERENCES inventario(id),
    CONSTRAINT ck_inventario_log_existencia_resultante
    CHECK (existencia_resultante >= 0)
    );

-- ------------------------------------------------------------
-- Compras
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS compra (
                                      id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      fecha_compra    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      empleado_id     BIGINT NOT NULL,
                                      CONSTRAINT pk_compra PRIMARY KEY (id),
    CONSTRAINT fk_compra_empleado
    FOREIGN KEY (empleado_id) REFERENCES empleado(id)
    );

CREATE TABLE IF NOT EXISTS compra_proveedor (
                                                compra_id       BIGINT NOT NULL,
                                                proveedor_id    BIGINT NOT NULL,
                                                CONSTRAINT pk_compra_proveedor PRIMARY KEY (compra_id, proveedor_id),
    CONSTRAINT fk_compra_proveedor_compra
    FOREIGN KEY (compra_id) REFERENCES compra(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_compra_proveedor_proveedor
    FOREIGN KEY (proveedor_id) REFERENCES proveedor(id)
    );

CREATE TABLE IF NOT EXISTS detalle_compra (
                                              compra_id       BIGINT NOT NULL,
                                              producto_id      BIGINT NOT NULL,
                                              proveedor_id    BIGINT NOT NULL,
                                              cantidad        INTEGER NOT NULL,
                                              precio_unitario NUMERIC(12,2),
    costo_total     NUMERIC(14,2),
    CONSTRAINT pk_detalle_compra PRIMARY KEY (compra_id, producto_id),
    CONSTRAINT fk_detalle_compra_compra
    FOREIGN KEY (compra_id) REFERENCES compra(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_detalle_compra_producto
    FOREIGN KEY (producto_id) REFERENCES producto(id),
    CONSTRAINT fk_detalle_compra_proveedor
    FOREIGN KEY (proveedor_id) REFERENCES proveedor(id),
    CONSTRAINT ck_detalle_compra_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_compra_precio CHECK (
                                                  precio_unitario IS NULL OR precio_unitario >= 0
                                              ),
    CONSTRAINT ck_detalle_compra_costo CHECK (
                                                 costo_total IS NULL OR costo_total >= 0
                                             )
    );

CREATE TABLE IF NOT EXISTS lote (
                                    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    detalle_compra_id   BIGINT NOT NULL,
                                    producto_id         BIGINT NOT NULL,
                                    creado_en           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    costo_unitario      NUMERIC(12,2) NOT NULL,
    cantidad_disponible INTEGER NOT NULL DEFAULT 0,
    cantidad_inicial    INTEGER NOT NULL,
    CONSTRAINT pk_lote PRIMARY KEY (id),
    CONSTRAINT fk_lote_producto
    FOREIGN KEY (producto_id) REFERENCES producto(id),
    CONSTRAINT ck_lote_costo CHECK (costo_unitario >= 0),
    CONSTRAINT ck_lote_cantidad_disponible CHECK (cantidad_disponible >= 0),
    CONSTRAINT ck_lote_cantidad_inicial CHECK (cantidad_inicial >= 0)
    );

-- ------------------------------------------------------------
-- Ventas
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS venta (
                                     id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     empleado_id     BIGINT NOT NULL,
                                     cliente_id      BIGINT NOT NULL,
                                     fecha_venta     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     sub_total       NUMERIC(14,2) NOT NULL,
    iva             NUMERIC(14,2) NOT NULL,
    total           NUMERIC(14,2) NOT NULL,
    CONSTRAINT pk_venta PRIMARY KEY (id),
    CONSTRAINT fk_venta_empleado
    FOREIGN KEY (empleado_id) REFERENCES empleado(id),
    CONSTRAINT fk_venta_cliente
    FOREIGN KEY (cliente_id) REFERENCES cliente(id),
    CONSTRAINT ck_venta_sub_total CHECK (sub_total >= 0),
    CONSTRAINT ck_venta_iva CHECK (iva >= 0),
    CONSTRAINT ck_venta_total CHECK (total >= 0)
    );

CREATE TABLE IF NOT EXISTS detalle_venta (
                                             venta_id        BIGINT NOT NULL,
                                             producto_id      BIGINT NOT NULL,
                                             cantidad        INTEGER NOT NULL,
                                             precio_unitario NUMERIC(12,2) NOT NULL,
    CONSTRAINT pk_detalle_venta PRIMARY KEY (venta_id, producto_id),
    CONSTRAINT fk_detalle_venta_venta
    FOREIGN KEY (venta_id) REFERENCES venta(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_detalle_venta_producto
    FOREIGN KEY (producto_id) REFERENCES producto(id),
    CONSTRAINT ck_detalle_venta_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_venta_precio CHECK (precio_unitario >= 0)
    );

-- ------------------------------------------------------------
-- Facturación
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS factura (
                                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       sale_id         BIGINT NOT NULL,
                                       numero_factura  VARCHAR(100),
    fecha_emision   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cliente_nit     VARCHAR(30),
    cliente_nombre  VARCHAR(150),
    estado          VARCHAR(50) NOT NULL,
    CONSTRAINT pk_factura PRIMARY KEY (id),
    CONSTRAINT fk_factura_venta
    FOREIGN KEY (sale_id) REFERENCES venta(id),
    CONSTRAINT uq_factura_numero UNIQUE (numero_factura)
    );

-- ------------------------------------------------------------
-- Configuración Global del Sistema
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS configuracion_sistema (
                                                     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                                     tasa_iva                NUMERIC(5,4) NOT NULL DEFAULT 0.1200,
    metodo_valoracion       VARCHAR(10) NOT NULL DEFAULT 'PEPS',
    resolucion_facturas     VARCHAR(100),
    serie_facturas          VARCHAR(20),
    correlativo_siguiente   BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_configuracion_sistema PRIMARY KEY (id),
    CONSTRAINT ck_config_metodo CHECK (metodo_valoracion IN ('PEPS', 'UEPS')),
    CONSTRAINT ck_config_iva CHECK (tasa_iva >= 0)
    );

-- ------------------------------------------------------------
-- Auditoría Global del Sistema
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bitacora_operacion (
                                                  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                                  empleado_id     BIGINT NOT NULL,
                                                  accion          VARCHAR(100) NOT NULL,
    modulo          VARCHAR(50) NOT NULL,
    detalle         TEXT,
    fecha           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bitacora_operacion PRIMARY KEY (id),
    CONSTRAINT fk_bitacora_empleado
    FOREIGN KEY (empleado_id) REFERENCES empleado(id)
    );

-- ------------------------------------------------------------
-- Índices para FKs y consultas frecuentes
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_empleado_area
    ON empleado(area_id);

CREATE INDEX IF NOT EXISTS idx_compra_proveedor_proveedor
    ON compra_proveedor(proveedor_id);

CREATE INDEX IF NOT EXISTS idx_compra_empleado
    ON compra(empleado_id);

CREATE INDEX IF NOT EXISTS idx_detalle_compra_producto
    ON detalle_compra(producto_id);

CREATE INDEX IF NOT EXISTS idx_detalle_compra_proveedor
    ON detalle_compra(proveedor_id);

CREATE INDEX IF NOT EXISTS idx_inventario_log_inventario
    ON inventario_log(inventario_id);

CREATE INDEX IF NOT EXISTS idx_lote_producto
    ON lote(producto_id);

CREATE INDEX IF NOT EXISTS idx_venta_empleado
    ON venta(empleado_id);

CREATE INDEX IF NOT EXISTS idx_venta_cliente
    ON venta(cliente_id);

CREATE INDEX IF NOT EXISTS idx_detalle_venta_producto
    ON detalle_venta(producto_id);

CREATE INDEX IF NOT EXISTS idx_factura_sale
    ON factura(sale_id);

CREATE INDEX IF NOT EXISTS idx_bitacora_empleado
    ON bitacora_operacion(empleado_id);

CREATE INDEX IF NOT EXISTS idx_bitacora_fecha
    ON bitacora_operacion(fecha);

COMMIT;

